replicaCount: 1

image:
  repository: ghcr.io/diamondlightsource/daq-queuing-service
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  runAsUser: 1000
  runAsGroup: 1000

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

livenessProbe:
  httpGet:
    path: /healthz
    port: http
readinessProbe:
  httpGet:
    path: /healthz
    port: http

# Send logs to the dodal graylog stream for now until a more suitable stream exists
config:
  blueapi_url: ""
  blueapi_call_constructor: "default"
  uvicorn:
    workers: 1
  logging:
    graylog:
      enabled: false
      url: ""
      level: "INFO"
    stream:
      enabled: true
      level: "DEBUG"

volumeMounts: []
volumes: []
nodeSelector: {}
tolerations: []
