class QueueError(Exception): ...


class TaskInProgressError(QueueError): ...


class TaskNotFoundError(QueueError): ...


class TaskNotInQueueError(QueueError): ...


class TaskIdInUseError(QueueError): ...


class NegativePositionError(QueueError): ...


class TaskAlreadyOwnedError(QueueError): ...


class TaskIsCompleteError(QueueError): ...
