on:
  workflow_call:
jobs:
  upload:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Download dist artifact
<<<<<<< before updating
        uses: actions/download-artifact@v7
=======
        uses: actions/download-artifact@v8
>>>>>>> after updating
        with:
          name: dist
          path: dist
      - name: Publish to PyPI using trusted publishing
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: false
